DROP DATABASE IF EXISTS estadistics;
CREATE DATABASE estadistics;
USE estadistics;
CREATE TABLE registre (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(500),
  data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
